mod 'puppet/nginx', '3.0.0'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'pltraining/dockeragent'
mod 'garethr/docker'
mod 'samuelson-dockeragent', '1.0.0'
mod 'puppetlabs-apt'
mod 'puppetlabs-translate'
mod 'puppetlabs-powershell'
mod 'puppetlabs-pwshlib'
mod 'puppetlabs-reboot'
